#! /bin/sh

NETIFACE=eth0

if [[ "$1" == "start" ]]; then
	subnet=$(sed "s/.*subnet=\([^ ]*\).*/\1/" /proc/cmdline)
	ifconfig $NETIFACE $subnet.2
	ifconfig $NETIFACE netmask 255.255.255.0
	ifconfig $NETIFACE broadcast $subnet.255
	ifconfig $NETIFACE up
fi
